project:
  type: website
  output-dir: _site

website:
  title: Restic Backups
  sidebar:
    style: docked
    contents:
      - index.qmd
      - quick-start.qmd
      - section: Setup
        contents:
          - configuration.qmd
          - sops.qmd
          - storage-costs.qmd
          - cli.qmd
      - section: Commands
        contents:
          - generic.qmd
          - voice-memos.qmd

format:
  html:
    theme: cosmo
    toc: true

execute:
  enabled: false
